# spdx-filecopyrighttext: 2026 cavassani
#
# spdx-license-identifier: cc0-1.0

name: espelho do reposit√≥rio do gitlab

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  mirror-gitlab-repo:
    uses: veloren/.github/.github/workflows/mirror.yml@main
    with:
      repository-url: https://gitlab.com/veloren/veloren.git
      rewrite-lfs: true
    secrets:
      token: ${{ secrets.MIRROR_TOKEN_GITHUB }}