# spdx-filecopyrighttext: 2026 cavassani
#
# spdx-license-identifier: cc0-1.0

name: desativar pull requests no github

on:
  pull_request_target:
    types:
      - opened

jobs:
  close-pull-request:
    uses: veloren/.github/.github/workflows/no-pr.yml@main
    permissions:
      pull-requests: write