name: autofix.ci # necessário para identificar com segurança o workflow

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  fix:
    name: rodar correção automática
    uses: prettier/shared-workflows/.github/workflows/automated-fix.yml@main
    permissions: {}
    with:
      repository: prettier/prettier