blank_issues_enabled: true

contact_links:
  - name: issue com a cli experimental
    url: https://github.com/prettier/prettier-cli/issues
    about: a cli experimental reside atualmente em um repositÃ³rio separado; abra uma issue lÃ¡
  
  - name: ğŸ¤” pergunta de suporte
    url: https://stackoverflow.com/questions/ask?tags=prettier
    about: ...

  - name: ğŸ“ ajuda com a extensÃ£o prettier do visual studio code
    url: https://github.com/prettier/prettier-vscode/issues
    about: bugs e sugestÃµes de melhorias para a extensÃ£o do prettier para o visual studio code