# esse workflow realizará uma instalação limpa das dependências
# do node.js, compilará o código-fonte e executará testes em
# diferentes versões de navegadores

name: ci de navegadores

on:
  push:
    branches: [ main, 4.x.x ]
  pull_requests:
    branches: [ main, 4.x.x ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser-name:
          - chromium
          - firefox

    steps:
    - uses: actions/checkout@v5
    - name: ${{ matrix.browser-name }}
      uses: actions/setup-node@v6
    - run: npm ci
    - run: npx playwright install --with-deps
    - run: npm run build --if-present
    - run: npm run test-chrome -- --browsers ${{ matrix.browser-name }}